export const FETCH_LOADING = "FETCH_LOADING";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOAD_USER = "LOAD_USER";

// PARCELS
export const PARCELS_LOADING = "PARCELS_LOADING";
export const LOAD_PARCELS = "LOAD_PARCELS";
export const CREATE_PARCEL = "CREATE_PARCEL";
export const EDIT_PICKUP_LOCATION = "EDIT_PICKUP_LOCATION";
export const EDIT_PICKUP_DESTINATION = "EDIT_PICKUP_DESTINATION";
export const CANCEL_DELIVERY = "CANCEL_DELIVERY";
